ImageLore/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from ImageLore import settings
from UserAndPermission.api.views import UserViewSet, PermissionViewSet
from ImageLoreCoreApp.views import *
from django.conf.urls.static import static

from ImageLoreFrontEnd.views import *
from ImageLoreCoreApp.views.image_view import *
from ImageLoreCoreApp.views.tag_view import *
from ImageLoreCoreApp.views.folder_view import *
from ImageLoreCoreApp.default_views import *

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'permissions', PermissionViewSet)

router.register(r'tags', TagViewSet)
router.register(r'aliases/tags', TagAliasViewSet)

router.register(r'tags/relations/tag', TagRelationViewSet)
router.register(r'tags/relations/post', TagPostRelationViewSet)
router.register(r'tags/relations/folder', TagFolderRelationViewSet)

router.register(r'folders', FolderView)
router.register(r'aliases/folders', FolderAliasView)

router.register(r'posts/images', ImagePostView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
    path('posts/<int:id>/', post_detail, name='post_detail'),
    path('auth/', include('dj_rest_auth.urls')),
]


if settings.USE_DJANGO_STATIC_FILE_SERVICE:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ImageLoreCoreApp/models.py
from django.contrib.auth.models import User
from django.db import models
import hashlib
from datetime import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


# 标签类


class Tag(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    # fullname = models.CharField(max_length=255, unique=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    IMG_ONLY = 1
    FOLDER_ONLY = 2
    BOTH = 3
    TYPE_CHOICES = [
        (IMG_ONLY, 'img_only'),
        (FOLDER_ONLY, 'folder_only'),
        (BOTH, 'both'),
    ]
    type = models.IntegerField(choices=TYPE_CHOICES, default=BOTH)
    color = models.CharField(max_length=8, default="#000000")
    father = models.ForeignKey('self', related_name='tagtree', null=True, blank=True, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    contribute = models.IntegerField(default=0)

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'color': self.color,
            'count': self.count,
            'contribute': self.contribute,
        }

    @staticmethod
    def update_count():
        # 获取所有根节点tags
        root_tags = Tag.objects.filter(father__isnull=True)

        for root_tag in root_tags:
            # 更新每个根节点下的tags的count
            root_tag.update_tag_count_recursive()

    def update_tag_count_recursive(self):
        # 获取当前tag直接标记的图片
        direct_images = set(self.tag_post_relations_tag.values_list('post', flat=True))

        # 获取子tags
        child_tags = self.tagtree.all()
        all_images = direct_images.copy()

        for child_tag in child_tags:
            # 递归获取子tag的所有图片（包括其子tag标记的图片）
            all_images |= child_tag.update_tag_count_recursive()
            # 合并图片集合，排除重复项
        trimmed_count = len(all_images)
        contribute_count = len(direct_images)
        # 更新当前tag的count
        self.count = trimmed_count
        self.contribute = contribute_count
        self.save()
        # print(all_images)
        return all_images

    def __str__(self):
        return f"[{self.id}]{self.name}"


PREFIX = f"%20%20"


def __get_sub_tree(tag, layer=0) -> []:
    child = Tag.objects.filter(father=tag)
    folder_count = TagFolderRelation.objects.filter(tag=tag)
    print(f'[{tag.name}]folder_count: ', folder_count)
    image_count = TagPostRelation.objects.filter(tag=tag)
    print(f'[{tag.name}]folder_count: ', image_count)
    child_response = []
    for tagChild in child:
        sub_response = __get_sub_tree(tagChild, layer + 1)
        child_response.append(sub_response)
    if len(child) == 0:
        return {
            'tag': tag,
            'depth': layer,
            'folder_count': folder_count.count(),
            'image_count': image_count.count(),
        }
    else:
        return {
            'tag': tag,
            'depth': layer,
            'folder_count': folder_count.count(),
            'image_count': image_count.count(),
            'children': child_response
        }


def get_whole_tree() -> []:
    queryset = Tag.objects.filter(father=None)
    response = []
    layer = 0
    for tag in queryset:
        response.append(__get_sub_tree(tag, layer + 1))
    print(response)
    return response


class TagRelation(models.Model):
    """
    标签和标签的父子关系
    """
    father_tag = models.ForeignKey(Tag, related_name='father_tag_relations', on_delete=models.CASCADE)
    child_tag = models.ForeignKey(Tag, related_name='child_tag_relations', on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"[{self.father_tag.id}]{self.father_tag.name} --> [{self.child_tag.id}]{self.child_tag.name}"


class TagAlias(models.Model):
    tag = models.ForeignKey(Tag, related_name='tag_aliases', on_delete=models.CASCADE)
    alias = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"[{self.tag.id}]{self.tag.name} <-- [{self.id}]{self.alias}"


class Folder(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    color = models.CharField(max_length=8, default="#000000")
    father = models.ForeignKey('self', related_name='folders', null=True, blank=True, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'color': self.color,
            'count': self.count,
        }

    @staticmethod
    def update_count():
        # 获取所有根节点tags
        root_tags = Folder.objects.filter(father__isnull=True)

        for root_tag in root_tags:
            # 更新每个根节点下的tags的count
            root_tag.update_folder_count_recursive()

    def update_folder_count_recursive(self):
        # 获取当前tag直接标记的图片
        direct_images = set(ImagePost.objects.filter(folder=self).values_list('id', flat=True))

        # 获取子tags
        child_tags = Folder.objects.filter(father=self)
        all_images = direct_images.copy()

        for child_tag in child_tags:
            # 递归获取子tag的所有图片（包括其子tag标记的图片）
            all_images |= child_tag.update_folder_count_recursive()
            # 合并图片集合，排除重复项
        trimmed_count = len(all_images)
        contribute_count = len(direct_images)
        # 更新当前tag的count
        self.count = trimmed_count
        self.contribute = contribute_count
        self.save()
        # print(all_images)
        return all_images

    def __str__(self):
        return self.name


class FolderAlias(models.Model):
    folder = models.ForeignKey(Folder, related_name='folder_aliases', on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True, null=True)
    alias = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"[{self.folder.id}]{self.folder.name} <-- [{self.id}]{self.alias}"


class TagFolderRelation(models.Model):
    tag = models.ForeignKey(Tag, related_name='tag_folder_relations_tag', on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, related_name='tag_folder_relations_folder', on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"[{self.folder.id}]{self.folder.name} <-- [{self.tag.id}]{self.tag.name}"


class ImagePost(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True, null=True)
    uploader = models.ForeignKey(User, related_name='image', on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, related_name='img_in_folder', on_delete=models.CASCADE)
    color = models.CharField(max_length=8, default="#000000")
    image = models.ImageField(upload_to='images/')
    thumbnail_small = models.ImageField(upload_to='thumbnails/small/', blank=True)
    thumbnail_medium = models.ImageField(upload_to='thumbnails/medium/', blank=True)
    date_uploaded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"[{self.id}]{self.name}--{self.uploader.get_full_name()}"


class TagPostRelation(models.Model):
    post = models.ForeignKey(ImagePost, related_name='tag_post_relations_post', on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, related_name='tag_post_relations_tag', on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"[{self.post.id}]{self.post.name} <-- [{self.tag.id}]{self.tag.name}"


@receiver(post_save, sender=TagPostRelation)
@receiver(post_delete, sender=TagPostRelation)
def update_tag_count(sender, instance, **kwargs):
    tag = instance.tag
    Tag.update_count()


@receiver(post_save, sender=ImagePost)
@receiver(post_delete, sender=ImagePost)
def update_folder_count(sender, instance: ImagePost, **kwargs):
    folder = instance.folder
    Folder.update_count()

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Anonymous Page?
      {% endblock %} - {{ site_title }}
    </title>
    <link href="/media/static/css/base.css" rel="stylesheet" />
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
    
    <link href="https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" />

    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/js/bootstrap.min.js"></script>
    <!-- popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
  </head>

  <body>
    <header>
      <nav id="navigator" class="navbar navbar-expand-lg fixed-top bg-white box-shadow">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <i class="bi bi-database" style="position: relative;"></i>
            {{ site_title }}
          </a>
          <button class="navbar-toggler bg-purple-700 rounded-3xl" style=" background-color: indigo; border-radius: 10px; color: white; padding: 5px" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar"><i class="bi bi-plus-square" style="position: relative;"></i></button>
          <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="/">
                  <i class="bi bi-cloud-upload" style="position: relative;"></i>
                  上传文件
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/posts/">
                  <i class="bi bi-card-image" style="position: relative;"></i>
                  图片库
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/tags/">
                  <i class="bi bi-tags" style="position: relative;"></i>
                  标签
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/folders/">
                  <i class="bi bi-folder-symlink" style="position: relative;"></i>
                  文件夹
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/search/">
                  <i class="bi bi-search" style="position: relative;"></i>
                  搜索
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/admin/">
                  <i class="bi bi-magic" style="position: relative;"></i>
                  站点管理
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/">
                  <i class="bi bi-house" style="position: relative;"></i>
                  账户
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div id="basic-container" class="container-fluid" style="margin-top:100px">
        <div id="body-container" class="row m-3 il-round-border">

          <div id="content-container" class="col-xl-8">
            <div id="content" class="il-item">
              {% block content %}

              {% endblock %}
            </div>
          </div>

          <div id="sidebar-container" class="col-xl-4">
            <div id="sidebar-test" class="il-item">
              {% comment %} 这是搜索条 {% endcomment %}
              <form class="d-flex mb-3">
                <input class="form-control me-2 flex-grow-1" type="text" placeholder="Search" />
                <button class="btn btn-primary" type="button">Go!</button>
              </form>

            {% comment %} 这是侧边栏占位符 {% endcomment %}
              {% block sidebar %}
                <div class="alert alert-danger" style="border-radius: 10px">
                  <strong>这里是侧边栏。</strong>
                  这里应该会出现有关图片的信息以及标签、文件夹列表。当前这里没有任何信息，<strong>你应该向网站运营人员反馈这个问题！</strong>
                </div>
              {% endblock %}

              {% comment %} 这是标签列表 {% endcomment %}
              <div class="card pr-2 sidebar_card">
                <h5 class="card-header text-white p-3" style="background-color: indigo;">
                  <i class="bi bi-tags" style="position: relative;"></i>
                  标签列表 ({{ tag_count }})
                </h5>
                <div class="card-body" style="padding-right: 10px">
                  {% for tag_tree in tag_set %}
                    <ul class="">
                      {% with node=tag_tree template_name="components/tree_view_component.html" %}
                        {%include "components/tree_view_component.html" %}
                      {% endwith %}
                    </ul>
                    {% empty %}
                    <div class="alert alert-info" style="border-radius: 10px">
                      <strong>您还没有创建标签。</strong>
                      只有您创建了标签，在侧边栏才能显示标签的树形结构。<strong>你可以在图片详情页中添加标签，或者使用导航栏上方的“标签”选项来创建第一个标签！</strong>
                    </div>
                  {% endfor %}
                </div>
              </div>


            </div>
          </div>
        </div>
      </div>
    </main>

    <footer>
      <div id="footer-container" class="container-fluid">
        <div id="footer" class="container-fluid">
          {% block footer %}
            <div id="copyright" class="row"></div>
          {% endblock %}

          <div id="copyright" class="row align-middle">
            <p style="text-align: center">Copyright © 2023-2024 {{ site_title }}. Powered by Jacky_Blackson. All rights reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

templates/front.html
{% extends 'base.html' %}

{% block title %}
  Front
{% endblock %}

{% block content %}
  <div class="alert alert-success alert-dismissible" style="border-radius: 10px">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <strong>欢迎来到 {{ site_title }}！</strong>
    这是一个使用文件夹和标签对图片进行分类标注和搜索的网站。下面是最新的20张图片，你也可以点击上方的导航栏浏览更多图片，或者使用右侧的文件夹以及标签树进行快速查询！
  </div>
  <div class="d-flex justify-content-around flex-wrap align-self-center">
    {% for image in image_set %}
      <div class="pt-2 align-self-center">
        <a href="/posts/{{ image.id }}/"><img class="card-img-top post_list" src="{{ root_url }}/{{ image.thumbnail_medium.url }}" alt="{{ image.name }}" style="border-color: {{ image.color }}" onload="adjustSize(this)" /></a>
      </div>
      {% empty %}
      <div class="alert alert-warning">
        <strong>目前网站上没有图片哦 >_></strong> 快点击上方导航栏上传第一张图片吧！
      </div>
    {% endfor %}
  </div>
{% endblock %}